name: Build, Test, and Deploy to Docker Hub

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: 'codeshayk/eauthor'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ${{ github.workspace }}
      github-token: '${{ secrets.GH_Packages }}'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*src/.*
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: '${{ env.github-token }}'

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: '${{ env.working-directory }}'
        
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: '${{ env.working-directory }}'
        
      - name: Run tests
        run: dotnet test --configuration Release --no-build --no-restore  --verbosity normal
        working-directory: '${{ env.working-directory }}'
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Hub
        if: always()
        run: docker logout
